[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
crypto_primitives = { path = "../crypto_primitives" }
auth = { path = "../auth" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
redis = { workspace = true }
rdkafka = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
bigdecimal = { workspace = true }
base64 = { workspace = true }
reqwest = { workspace = true }
x25519-dalek = { workspace = true }
